import { Feed } from "../../pages/Mypage";

export const mypageData: Feed = {
    nickname: "라니",
    profilePic: "https://ojsfile.ohmynews.com/STD_IMG_FILE/2022/0518/IE002993026_STD.JPG",
    feeds: [
        {
            feedId: 1,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/1.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 2,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/2.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 3,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/3.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집", "분위기맛집", "분위기맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 4,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/4.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 5,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/5.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 6,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/6.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 7,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/7.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 8,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/8.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 9,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/9.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 10,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/1.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 11,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/2.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        },
        {
            feedId: 12,
            feedPic: `${process.env.PUBLIC_URL}/sampleimg/3.png`,
            comment: '매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊매장이 너무 예뻐요!! 카페 이름처럼 매장 안이 모두 노란색이에요🌻 그래서 화사하고 너무 좋아요!! 직원분도 너무너무 친절하세요!!! 휘핑크림 여부도 물어봐주시고 조금 기다렸는데 기다려주셔서 감사하다고 해주시고... 자주 찾아올 것 같아요😊',
            tags: ["디저트맛집", "커피맛집", "분위기맛집"],
            shopId: 13,
            shopName: "그린 플레이트",
            shopAddress: "서울시 광진구 무슨동",
            shopThumbnail: "https://img.hankyung.com/photo/202209/01.31363897.1.jpg",
            isScrap: false,
        }
    ],
    feedCount: 12
}